apiVersion: v1
kind: Pod
metadata:
  name: fss-dynamic-app
  namespace: app2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/mnt
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fss-pvc-v2
