apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fss-pvc-v2
  namespace: app2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: fss-pv-app2
